name: CI

on:
  push:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.set-matrix.outputs.apps }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          apps=$(ls generated | jq -R -s -c 'split("\n")[:-1]')
          echo "apps=$apps" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ matrix.app }}
    needs: generate-matrix
    strategy:
      matrix:
        app: ${{ fromJSON(needs.generate-matrix.outputs.apps) }}
    uses: spacelift-io/flows-community-registry/.github/workflows/build-app-version.yml@main
    with:
      working-directory: generated/${{ matrix.app }}
